before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    binary: websocket-server
    ldflags:
      - -s -w
    hooks:
      pre:
        - go mod download
        - apt-get update
        - apt-get install -y gcc libc6-dev

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    files:
      - none*

dockers:
  - image_templates:
      - "websocket-server:{{ .Version }}"
      - "websocket-server:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - go.mod
      - go.sum
      - "*.go"
