before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: websocket-server
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: "{{ .Binary }}"
    files:
      - none*

dockers:
  - image_templates:
      - "websocket-server:{{ .Version }}"
      - "websocket-server:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
