services:
  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - app-network
    volumes:
      - ./data:/app/data  # SQLite 数据持久化

networks:
  app-network:
    driver: bridge
