# 启用 BuildKit
x-build: &build-options
  context: .
  dockerfile: Dockerfile
  args:
    BUILDKIT_INLINE_CACHE: 1

services:
  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: websocket-server:latest
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    networks:
      - app-network
    volumes:
      - ./data:/app/data  # SQLite 数据持久化

networks:
  app-network:
    driver: bridge
